services:
  - type: web
    name: uxcellence-spin-wheel
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: "./dist"
    envVars:
      - key: NODE_VERSION
        value: 18.x
    healthCheckPath: /
